[package]
name = "nu-build"
version = "0.1.0"
authors = ["Yehuda Katz <wycats@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.102", features = ["derive"] }
lazy_static = "1.2.0"
serde_json = "1.0.35"
toml = "0.5.5"
